version: '3.3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:15.0.2
    container_name: senior-talents-identity-provider
    restart: unless-stopped
    ports:
      - "8181:8080"
    environment:
      DB_VENDOR: H2
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_USER: keycloak
      KEYCLOAK_PASSWORD: secret
    networks:
      - keycloak-network

networks:
  keycloak-network:
    driver: bridge
